name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Job 1 (Explore) is starting."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "ğŸ Job 1 status is ${{ job.status }}."

  Test-Code-Quality:
    runs-on: ubuntu-latest
    needs: Explore-GitHub-Actions
    steps:
      - run: echo "ğŸ§ª Job 2 (Test) is starting automated tests..."
      - run: sleep 15
      - run: echo "âœ… Job 2 finished."

  Deploy-to-Production:
    runs-on: ubuntu-latest
    needs: Test-Code-Quality
    steps:
      - run: echo "ğŸš€ Job 3 (Deploy) is deploying the code to production!"
      - run: sleep 10
      - run: echo "ğŸ Deployment complete."
